server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - RemoveHopByHopHeaders=
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
