server:
  port: 8081
spring:
  application:
    name: user-service\
  #security:
  #  oauth2:
  #    resourceserver:
  #      jwt:
  #        issuer-uri: http://localhost:8080/realms/payments
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/payments   #?options=-c%20TimeZone=Asia/Kolkata
    schema: public
    driver-class-name: org.postgresql.Driver
    username: payments
    password: payments
  jpa:
    hibernate.ddl-auto: none #as we are using liquibase
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


dev:
  security:
    disabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
