server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: payments
    password: payments
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
