server:
  port: 8081
spring:
  application:
    name: user-service\
  #autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/payments

  datasource:
    url: jdbc:postgresql://localhost:5432/payments   #?options=-c%20TimeZone=Asia/Kolkata
    schema: public
    driver-class-name: org.postgresql.Driver
    username: payments
    password: payments
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true

   # will point to Keycloak later

dev:
  security:
    disabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
