server:
  port: 8082
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    schema: public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
